export enum ErrorCode {
  // 400번대 에러
  BAD_REQUEST = 'BAD_REQUEST', // 400
  UNAUTHORIZED = 'UNAUTHORIZED', // 401
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED', // 402
  FORBIDDEN = 'FORBIDDEN', // 403
  NOT_FOUND = 'NOT_FOUND', // 404
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED', // 405
  NOT_ACCEPTABLE = 'NOT_ACCEPTABLE', // 406
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT', // 408
  CONFLICT = 'CONFLICT', // 409
  GONE = 'GONE', // 410
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE', // 413
  URI_TOO_LONG = 'URI_TOO_LONG', // 414
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE', // 415
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY', // 422
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS', // 429
  // 500번대 에러
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR', // 500
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED', // 501
  BAD_GATEWAY = 'BAD_GATEWAY', // 502
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE', // 503
  GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT', // 504
  HTTP_VERSION_NOT_SUPPORTED = 'HTTP_VERSION_NOT_SUPPORTED', // 505
  INSUFFICIENT_STORAGE = 'INSUFFICIENT_STORAGE', // 507
  NETWORK_AUTHENTICATION_REQUIRED = 'NETWORK_AUTHENTICATION_REQUIRED', //511

  // 클라이언트 에러
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',

  // DB에러
  DB_UNIQUE_CONSTRAINT = 'DB_UNIQUE_CONSTRAINT',
  DB_FOREIGN_KEY = 'DB_FOREIGN_KEY',
  DB_NOT_FOUND = 'DB_NOT_FOUND',
}
