const YONGSAN_HALAL_STORES = [
  {
    bs_no: 'PENDING_EID_HALAL',
    sto_name: '이드(EID) 할랄 코리안 푸드',
    sto_name_en: 'EID Halal Korean Food',
    sto_address: '서울특별시 용산구 우사단로10길 67',
    sto_phone: '070-8899-8210',
    sto_img:
      'https://checkeatstoreimg.blob.core.windows.net/dummy-store/EID.png',
    sto_status: 0,
    sto_halal: 1,
    sto_type: '음식점',
    sto_latitude: 37.5323774,
    sto_longitude: 126.9991854,
  },
  {
    bs_no: 'PENDING_SULTAN_KEBAB',
    sto_name: '술탄 케밥',
    sto_name_en: 'Sultan Kebab',
    sto_address: '서울특별시 용산구 보광로 126',
    sto_phone: '02-749-3890',
    sto_img:
      'https://checkeatstoreimg.blob.core.windows.net/dummy-store/SULTAN.jpg',
    sto_status: 0,
    sto_halal: 1,
    sto_type: '음식점',
    sto_latitude: 37.5335,
    sto_longitude: 126.9941,
  },
  {
    bs_no: 'PENDING_KERVAN_RES',
    sto_name: '케르반 레스토랑',
    sto_name_en: 'Kervan Restaurant (Itaewon)',
    sto_address: '서울특별시 용산구 이태원로 190',
    sto_phone: '02-792-4767',
    sto_img:
      'https://checkeatstoreimg.blob.core.windows.net/dummy-store/KERVAN.jpg',
    sto_status: 0,
    sto_halal: 1,
    sto_type: '음식점',
    sto_latitude: 37.53433,
    sto_longitude: 126.99518,
  },
  {
    bs_no: 'PENDING_KERVAN_BAKERY',
    sto_name: '케르반 베이커리&카페',
    sto_name_en: 'Kervan Bakery & Cafe',
    sto_address: '서울특별시 용산구 이태원로 208',
    sto_phone: '02-790-5585',
    sto_img:
      'https://checkeatstoreimg.blob.core.windows.net/dummy-store/KERVAN_BAKERY.jpeg',
    sto_status: 0,
    sto_halal: 1,
    sto_type: '카페/베이커리',
    sto_latitude: 37.53425,
    sto_longitude: 126.9967,
  },
  {
    bs_no: 'PENDING_HOME_KIM',
    sto_name: '집밥김선생(스타캐터링)',
    sto_name_en: 'Home Cooking Master Kim (Starcatering)',
    sto_address: '서울특별시 용산구 녹사평대로46길 28',
    sto_phone: '02-792-3731',
    sto_img:
      'https://checkeatstoreimg.blob.core.windows.net/dummy-store/HOME_KIM.png',
    sto_status: 0,
    sto_halal: 1,
    sto_type: '음식점',
    sto_latitude: 37.5364,
    sto_longitude: 126.9879,
  },
  {
    bs_no: 'PENDING_MR_KEBAB',
    sto_name: '미스터케밥',
    sto_name_en: 'Mr. Kebab',
    sto_address: '서울특별시 용산구 이태원로 192',
    sto_phone: '070-7758-1997',
    sto_img:
      'https://checkeatstoreimg.blob.core.windows.net/dummy-store/MR_KEBAB.png',
    sto_status: 0,
    sto_halal: 1,
    sto_type: '음식점',
    sto_latitude: 37.5343797,
    sto_longitude: 126.995424,
  },
  {
    bs_no: 'PENDING_HALAL_GUYS',
    sto_name: '할랄가이즈 이태원점',
    sto_name_en: 'The Halal Guys (Itaewon)',
    sto_address: '서울특별시 용산구 이태원로 187, 2층',
    sto_phone: '02-794-8308',
    sto_img:
      'https://checkeatstoreimg.blob.core.windows.net/dummy-store/HALAL_GUYS.png',
    sto_status: 0,
    sto_halal: 1,
    sto_type: '음식점',
    sto_latitude: 37.53456,
    sto_longitude: 126.99405,
  },
];

module.exports = { YONGSAN_HALAL_STORES };
